- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
     
    - name: Capture Transaction ID
      debug:
        msg: "{{ transaction_id }}"
